name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # ========================
  # 1️⃣ JOB TEST
  # ========================
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn clean test

  # ========================
  # 2️⃣ JOB BUILD
  # ========================
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn clean package -DskipTests
      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  # ========================
  # 3️⃣ JOB REDEPLOY RENDER
  # ========================
  redeploy:
    runs-on: ubuntu-latest
    needs: build

    # chỉ deploy khi push vào main (không deploy khi PR)
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}